FROM python:3.10-slim AS build
WORKDIR /code
COPY requirements.txt coco.names ./
RUN pip install --no-cache-dir -r /code/requirements.txt
# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 docker.io -y
COPY ./app /code/app

CMD ["python", "app/main.py"]